### ISSUE TITLE
Music app (native) is crashing while trying to launch it.

### ISSUE THREAD

**Issue by Sathish-Chandrasekaran-Pinayour** [Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1#2]
**Issue :**
The native music app (which comes bundled with the Android system) is crashing while trying to launch the same.

**Steps to Reproduce :**
1. Flash the Android Nougat image for RPI 3.
2. Click on the Music app once the device comes up.

**Expected Result :**
The Music app should get launched successfully.

**Actual Result :**
The Music app is crashing.

**User Impact:**
High, since the user will not be able to use the default Music app.

**Additional Notes**
This issue is not seen with 3rd party music apps.

**Logcat**
[log_music_app_open_crash.txt](https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/files/1714038/log_music_app_open_crash.txt)

**Comment by anutriEximius** [comment]
@Sathish-Chandrasekaran-Pinayour 

From the attached logcat, we can see that there is a security exception causing this crash :
--------- beginning of crash
01-24 16:43:53.525 E/AndroidRuntime( 1824): FATAL EXCEPTION: main
01-24 16:43:53.525 E/AndroidRuntime( 1824): Process: com.android.music, PID: 1824
01-24 16:43:53.525 E/AndroidRuntime( 1824): java.lang.RuntimeException: Unable to create service com.android.music.MediaPlaybackService: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

The root cause of the issue is:
World-readable files can be a security flaw. So android first deprecated it and then completely removed it. MODE_WORLD_READABLE was deprecated in versions till Android M. But in Android N it is no longer supported and throws SecurityException. So try a different mode. I used Context.MODE_PRIVATE and it worked. This is already fixed in latest version of android oreo.

I have already applied the changes with which music app gets launched successfully:
-        mPreferences = getSharedPreferences("Music", MODE_WORLD_READABLE | MODE_WORLD_WRITEABLE);
+        mPreferences = getSharedPreferences("Music", MODE_PRIVATE);

You can refer this link where they have mentioned the changes.
https://android.googlesource.com/platform/packages/apps/Music/+/6036ce6127022880a3d9c99bd15db4c968f3e6a3

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@anutriEximius : Looks good. You can back port the changes from Oreo to Nougat. Kindly create a pull request and get the changes merged to the master branch.

**Comment by anutriEximius** [comment]
Hi @Sathish-Chandrasekaran-Pinayour 
I have made the pull request kindly review it. This is already tested and works fine.
https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/9

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@anutriEximius : I have merged your pull request : https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/9 to the master branch.

Will close this issue.
