### ISSUE TITLE
Gallery app (native) is crashing while trying to launch the same.

### ISSUE THREAD

**Issue by Sathish-Chandrasekaran-Pinayour** [Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1#3]
**Issue :**
The native gallery app (which comes bundled with the Android system) is crashing while trying to launch the same.

**Steps to Reproduce :**
1. Flash the Android Nougat image for RPI 3.
2. Click on the Gallery app once the device comes up.

**Expected Result :**
The Gallery app should get launched successfully.

**Actual Result :**
The Gallery app is crashing.

**User Impact:**
High, since the user will not be able to use the default Gallery app.

**Additional Notes**
This issue is not seen with 3rd party apps.

**Logcat**
[log_gallery_app_open_crash.txt](https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/files/1714041/log_gallery_app_open_crash.txt)

**Comment by anutriEximius** [comment]
@Sathish-Chandrasekaran-Pinayour 

This issue is specific to gallery application, By checking the log we can see that its issue with the application configuration incompatible to opengl.

--------- beginning of crash
01-24 16:53:35.732 E/AndroidRuntime( 1883): FATAL EXCEPTION: GLThread 189
01-24 16:53:35.732 E/AndroidRuntime( 1883): Process: com.android.gallery3d, PID: 1883
01-24 16:53:35.732 E/AndroidRuntime( 1883): java.lang.IllegalArgumentException: No config chosen
01-24 16:53:35.732 E/AndroidRuntime( 1883): 	at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:888)
01-24 16:53:35.732 E/AndroidRuntime( 1883): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
01-24 16:53:35.732 E/AndroidRuntime( 1883): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1412)
01-24 16:53:35.732 E/AndroidRuntime( 1883): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

So, you can fix this issue by adding the following in the path: android-7.1.2_r19_rpi3\packages\apps\Gallery2\src\com\android\gallery3d\ui

In GLRootView ,

if (ApiHelper.USE_888_PIXEL_FORMAT) {
            setEGLConfigChooser(8, 8, 8, 8, 16, 0);
 
instead of setEGLConfigChooser(8, 8, 8, 0, 0, 0);

Please review the pull request: https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/13

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
Have merged the pull request to master branch. Closing this ticket
