### ISSUE TITLE
Audio is not getting routed to headphone/headset connected to 3.5 mm jack port

### ISSUE THREAD

**Issue by Sathish-Chandrasekaran-Pinayour** [Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1#4]
**Issue :**
Audio is not getting routed to headphone/headset connected to 3.5 mm jack port. It continues to be heard on the HDMI TV Speakers.

**Steps to Reproduce :**
1. Flash the Android Nougat image for RPI 3.
2. Play local/streaming media using any of the following ways :
    1. Settings --> Sound --> Toggle the volume panel of Media/Alarm/Notification streams.
    2. Push a media (any supported audio/video format) to sdcard and play it using native/3rd party apps.
    3. Play a streaming media (Saavn/YouTube etc.) via a web browser.
3. Insert a Headset/Headphone in to the 3.5 mm jack and observe the behaviour.

**Expected Result :**
Audio should get routed to headphone/headset as soon as it is inserted in to the 3.5 mm jack port.

**Actual Result :**
Audio doesn't get routed to headphone/headset once inserted in to the 3.5 mm jack port. Instead, the audio continues to be heard on the HDMI TV Speakers.

**User Impact:**
High, since this is a poilcy breach.

**Comment by vinaykumar-eximius** [comment]
There is config.txt file available in boot partition. In configuration file hdmi_force_hotplug is set to 1, this force the raspberry pi board to use HDMI mode. Also hdmi_drive set to 2, so that sound will be sent over HDMI cable.

To route sound on 3.5 mm jack port add following two lines in config.txt in boot partition.
**hdmi_ignore_edid_audio=1
hdmi_force_edid_audio=0**

Setting hdmi_ignore_edid_audio to 1 pretends that all audio formats are unsupported by the display. This means ALSA will default to the analogue audio jack.
Setting hdmi_force_edid_audio to 0 for default audio setting.

After editing configuration file reboot your device. 

Also you can change config.txt file present in source code of android-7.1.2_r19_rpi3  at location android-**_7.1.2_r19_rpi3/device/brcm/rpi3/boot/config.txt_** for your next system image build.

Please correct me if I am wrong.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Thank you for the explanation. However, please check these :
1. hdmi_drive=2 implies that the default audio out is set to HDMI. So, shouldn't this variable also be changed to bring audio on 3.5mm jack port?
2. The Bangalore team also changed the config.txt as follows to bring audio on 3.5 mm jack
    hdmi_drive=1
    hdmi_ignore_edid_audio=1
    audio_pwm_mode=2
    disable_audio_dither=1
3. Please take a logcat with and without the changes to have a better understanding.

**Comment by vinaykumar-eximius** [comment]
As per your comment I played music with both the changes and took logs. Music player working fine with both cases and by observing and comparing logs, so far both logs are same and flow of code is also same.
Only one error I found.
 **_WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found_**

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : The error pertaining to WVMExtractor can be ignored. Please attach the logs for the  following :
1. Keep the Config file as is and do a music playback.
2. Do the config changes you mentioned and do a music playback.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Please create a pull request and commit the changes to the repository. We have tested your changes here. It works fine.

**Comment by vinaykumar-eximius** [comment]
Hi Sathish  pull request is created you an merge it on your repository.

**Comment by vinaykumar-eximius** [comment]
Have created the pull request : https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/10
please review

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Thanks. Have reviewed and merged the changes.

Closing this ticket
