### ISSUE TITLE
There is no home screen or native apps like Music, Gallery etc. in the App Browser

### ISSUE THREAD

**Issue by Sathish-Chandrasekaran-Pinayour** [Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1#6]
**Issue :**
There is no home screen or native apps like Music, Gallery etc. in the App Browser once the device comes up after flashing the Android Nougat 7.1.2 binaries from source.

**Steps to Reproduce :**
1. Flash the Android Nougat 7.1.2 binaries built from source for RPI 3.
2. Observe the Home Screen & App Browser.

**Expected Result :**
There should be a Home Screen populated with a couple of system apps backed by a launcher and the native apps should also be present under the App Browser as depicted in the attachment :
![home screen - expected](https://user-images.githubusercontent.com/36184426/36072483-58bb4094-0f46-11e8-8cef-ea372efc749a.png)
![app browser - expected](https://user-images.githubusercontent.com/36184426/36072495-90b309c8-0f46-11e8-95f6-8eae1079bce8.png)

**Actual Result :**
The Home Screen is empty while the App Browser consists of only "Settings" and "Browser" app.

**User Impact:**
Medium, since this will impact only the UI Screen.

**Comment by vinaykumar-eximius** [comment]
There is no home screen populated after flashing the Android Nougat 7.1.2 because there is no default luncher application enabled during the android build. 
To enable luncher after device boot-up, its need to be change in make file of raspberry pi present in **android-7.1.2_r19_rpi3/device/brcm/rpi3/rpi3.mk**. There is a application packages entry in the target product .mk to add native applications in android image during build.

The list of application is present in **android-7.1.2_r19_rpi3/packages/apps** directory of build source. As you can see there are several native application like Settings, Browser etc. present in the directory. 
To lunch application at boot time you have to add name of product/application you want to **_PRODUCT_PACKAGES_** list in rpi3.mk. 

Follow these steps to enable launcher and other native application.
1) Goto **packages/apps** directory of build source. For example **_android-7.1.2_r19_rpi3/packages/apps_** in my case.
2) See the applications that you want is available or not by simply typing **_ls_ -l** command.
It shows list of native applications that present in your android source code.
It generate list of application as you can show bellow and check that application is present or not.

BasicSmsReceiver
ExactCalculator
PhoneCommon
TvSettings
Bluetooth
Contacts
Gallery
Messaging
SpeechRecorder
UnifiedEmail
Browser2
ContactsCommon
Music
Calculator
Launcher2 etc.

3) Goto **android-7.1.2_r19_rpi3/device/brcm/rpi3/** directory and type **_vi rpi3.mk_** to edit file.
4) Goto the line where **PRODUCT_PACKAGES** is start.
5) Add name of application that you want to show in native application list.
For example:

PRODUCT_PACKAGES += \\
    Launcher2 \\
    LeanbackLauncher \\
    Settings \\
    Browser2
6) Save and Close the file.
7) Build new system image and flash it on sdcard.

By doing this changes you can see native application in your system. You can also add your custom application in package list with appropriate Android make file and later add the application name in rpi3.mk.

**NOTE: Be aware while modifying Makefile as it susceptible to space and tabs.**

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Good analysis. A few queries though 
1) Our build is meant for TV. Hence, using a LeanBack Launcher seems right. Please follow this procedure to integrate Leanback Launcher into our workspace and check if it is stable :
    1. Find latest version of Launcher binary in following link.
        https://developers.google.com/android/nexus/drivers#fugu
    2. Before doing Android build step, Extract the binary package on top of the Android source, Then      
        LeanbackLauncher apk will be placed in the path below.
        vendor/google/fugu/proprietary/LeanbackLauncher.apk
     3. After that do Android build and write target filesystem. Check Launcher2 is replaced by 
        LeanbackLauncher on target SD card's /system/priv-app folder.
     4. If both launchers co-exist. Remove Launcher2 by mounting the SD card on host PC or you can also 
         ignore both Launcher 2 & Launcher 3 from the PRODUCT_PACKAGES list.
**If Leanback Launcher is not stable, use Launcher 3 and test**
2) Please attach the screenshot of Home Screen & App Browser once you make the changes.

**Comment by vinaykumar-eximius** [comment]
I do the same steps that mentioned above. When system is boot-up  after successful build and flashing image on sdcard, home screen of device is look different then screen shot attached by you in above comment. I attached a screen shot of my Raspberry-Pi. 

![img_20180213_110748386](https://user-images.githubusercontent.com/36193846/36135930-efb2c9e0-10b3-11e8-8624-f25219a52d7c.jpg)

I used **Nexus Player binaries for Android 7.1.2 (N2G48C)**  Launcher TV binary.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Yes, the Home Screen i have attached is from Launcher 3. The Bangalore team tried integrating LeanBack Launcher. However, since we didn't find it to be stable, we reverted to using Launcher 3.  However, we would certainly prefer to use LeanBack launcher (provided we find a stable version) since it is recommended for TV builds. 

Can you please check the following :
 1. Please add more apps and check if you are able to get them listed in the App Browser.
 2. Set the current Date & Time and connect to WiFi.
 3. Attach the screenshot of Home & App Browser similar to what i have attached for Launcher 3

**Comment by vinaykumar-eximius** [comment]
I successfully connected system with WiFi and also set date and time. There is no application browsing icon in launcher, only Settings and Network Settings icons are display as default home screen. Application can be started by doing following steps: 1) Open Settings 2) Goto the App icon on setting list 3) Select application you want to open and click 4) Click on open.
I tried to open several applications like Music player and Calculator etc., however Gallery app is crashing on started, and not be able to open Browser app.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius ,
If you are able to to set date and time and connect to WiFi, then looks like you have found a stable version of LeanBack Launcher apk. However, a LeanBack launcher would look like this 

![leanback_launcher](https://user-images.githubusercontent.com/36184426/36138133-2fa1dfe6-10be-11e8-9a77-a45aafcb71be.jpeg)

Guess, it should be possible to sideload apps to the Home Screen. Please try the following changes :
Under /device/brcm/rpi3
1. In rpi3_core_hardware.xml, add  : \<feature name="android.software.home_screen" />
2. In rpi3.mk , remove "Launcher2" from PRODUCT_PACKAGES

Build only the system image (make -j256 systemimage) and flash.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Please find attached the "Sideload Launcher" apk. Install it and you should be able to view the apps.
[Sideload Launcher Android TV_v1.05_apkpure.com.zip](https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/files/1719795/Sideload.Launcher.Android.TV_v1.05_apkpure.com.zip)

**Comment by vinaykumar-eximius** [comment]
I installed and its working fine. Sideload icon is appear in home screen.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : I would prefer using Launcher 3 since it is preferred for handheld devices. Even though, our build is meant for TV, i would recommend to use Launcher 3 + Home Screen capability to give a "tablet-like" feel to our device. Please make the necessary changes and test.

**Comment by vinaykumar-eximius** [comment]
I integrate Launcher 3 and connect it with wifi, also set date and time without any issue. Able to play music over web browser.
Native applications are show in application browser menu.

![screen1](https://user-images.githubusercontent.com/36193846/36191362-c101ba46-1182-11e8-991a-bbea688f76a4.png)

![screen2](https://user-images.githubusercontent.com/36193846/36191367-c9746818-1182-11e8-9029-7d66d5729cf7.png)

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@vinaykumar-eximius : Looks good. Can you please create a pull request for the changes?

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
The pull request : https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/12 has been merged to master. Closing this ticket
